### ISSUE TITLE
error when trying to create a starter-gatsby-project

### ISSUE THREAD

**Issue by rileyshu53** [ArcBlock/forge-dapp-starters#11]
Problem reproduction
-----
```bash
npm install -g @arcblock/forge-cli forge-gatsby-starter
forge init
forge start
forge create-project hello-forge
```

after the `forge create-project hello-forge`, console shows this error: 
```
? Select a starter template: forge-gatsby-starter
? Running chain node graphql endpoint: http://localhost:8210/api
{ Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/forge-gatsby-starter/starter.config.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by wangshijun** [comment]
fixed and renamed to `forge-xmark-starter`
